import ui,time,json
from pathlib import Path
captures=[];events=[]
def event(text):events.append({'time':time.time(),'event':text});print(text,flush=True)
def shot(role,name):ui.screenshot(role,name)
try:
    ui.click('phone','Back');time.sleep(.3)
    ui.call('phone','POST','/back',{});time.sleep(.3)
    ui.click('phone','Open chat with Username');time.sleep(.5)
    for role in ['phone','emulator']:captures.append(ui.record_start(role,'calls-final'))
    event('Recording starts with both conversations open')
    time.sleep(3)
    ui.click('emulator','Start voice call');event('Emulator starts voice call')
    ui.wait_label('phone','Answer',20);time.sleep(2)
    ui.click('phone','Answer');event('Physical phone answers incoming call')
    ui.wait_label('phone','End',25);ui.wait_label('emulator','End',10)
    ui.wait_label('phone','Connected',20);event('Both call interfaces connected')
    time.sleep(5)
    ui.click('phone','Mute');event('Microphone muted by user')
    time.sleep(2)
    ui.click('phone','Unmute');event('Microphone unmuted by user')
    time.sleep(3)
    ui.adb('phone','shell','input','keyevent','KEYCODE_HOME');event('Physical phone goes to Home while call continues')
    time.sleep(3)
    ui.adb('phone','shell','input','swipe','540','40','540','1600','500');time.sleep(1)
    ui.wait_label('phone','Call in progress',5)
    shot('phone','calls-final-background')
    event('Call in progress notification and microphone indicator shown')
    Path('/tmp/mknoon-play-videos/calls-final-phone-services.txt').write_bytes(ui.adb('phone','shell','dumpsys','activity','services','com.mknoon.app'))
    time.sleep(5)
    ui.adb('phone','shell','cmd','statusbar','collapse');time.sleep(.4)
    ui.adb('phone','shell','am','start','-n','com.mknoon.app/.MainActivity');time.sleep(.6)
    ui.wait_label('phone','End',10);event('Return to ongoing call with elapsed timer')
    time.sleep(3)
    ui.click('phone','End');event('User ends call')
    time.sleep(2)
    ui.adb('phone','shell','input','keyevent','KEYCODE_HOME')
    ui.adb('phone','shell','input','swipe','540','40','540','1600','500');time.sleep(.7)
    assert not ui.visible('phone','Call in progress')
    shot('phone','calls-final-ended');event('Ongoing-call notification is gone')
    time.sleep(3)
except Exception as error:
    event('Capture failure: '+str(error))
finally:
    for rec in captures:ui.record_stop(rec)
    Path('/tmp/mknoon-play-videos/calls-final-state.json').write_text(json.dumps({'captures':captures,'events':events},indent=2))
    event('Recorders stopped and files copied')
