package com.mknoon.app.call

import java.nio.charset.StandardCharsets
import java.util.UUID

internal data class CallWakePayload(
    val nativeCallId: UUID,
    val callHandle: String,
    val wakeHandle: String,
    val receivedAtMs: Long,
    val expiresAtMs: Long,
)

internal enum class CallPayloadRejectionReason {
    NOT_DATA_ONLY,
    INVALID_SHAPE,
    DUPLICATE_KEY,
    TOO_LARGE,
    MALFORMED,
    STALE,
    TOO_FAR_FUTURE,
}

/**
 * The closed call-diagnostic reason for a rejected wake. A stale wake reads
 * `expired`. The other reasons have no own value in the shared schema (the
 * relay rejects unknown values), so they keep `rejected_payload`.
 */
internal fun callWakeRejectionDiagnosticReason(reason: CallPayloadRejectionReason): String =
    when (reason) {
        CallPayloadRejectionReason.STALE -> "expired"
        else -> "rejected_payload"
    }

internal sealed interface CallPayloadParseResult {
    data class Accepted(val payload: CallWakePayload) : CallPayloadParseResult

    data class Rejected(
        val reason: CallPayloadRejectionReason,
    ) : CallPayloadParseResult
}

internal class CallPayloadParser(
    private val nowMs: () -> Long,
) {
    companion object {
        const val MAX_PAYLOAD_BYTES = 256
        const val MAX_FUTURE_SKEW_MS = 45_000L

        /**
         * How far the caller's clock may run ahead of this device. Dart's
         * envelope codec accepts the same lead
         * (`SecureCallEnvelopeCodec.maxFutureClockSkew`).
         */
        const val MAX_CALLER_CLOCK_LEAD_MS = 30_000L

        /**
         * A wake's `e` is the caller's exact invite expiry, kept as is for
         * relay-row matching. It may lie up to the 45 s lifetime plus the
         * caller clock lead ahead of this clock (beta 2026-09-25: a callee
         * 13 s behind got `e` 53 s ahead). Local ringing and admission stay
         * bounded to [MAX_FUTURE_SKEW_MS] on the local clock.
         */
        const val MAX_CALLER_EXPIRY_AHEAD_MS =
            MAX_FUTURE_SKEW_MS + MAX_CALLER_CLOCK_LEAD_MS

        private val EXPECTED_KEYS = setOf("v", "w", "c", "h", "e")
        private val STRICT_MILLISECONDS = Regex("^[1-9][0-9]{0,18}$")
    }

    fun parse(
        entries: List<Pair<String, String>>,
        hasNotification: Boolean,
    ): CallPayloadParseResult {
        if (hasNotification) return rejected(CallPayloadRejectionReason.NOT_DATA_ONLY)

        var payloadBytes = 0L
        for ((key, value) in entries) {
            payloadBytes += key.toByteArray(StandardCharsets.UTF_8).size.toLong()
            payloadBytes += value.toByteArray(StandardCharsets.UTF_8).size.toLong()
            if (payloadBytes > MAX_PAYLOAD_BYTES) {
                return rejected(CallPayloadRejectionReason.TOO_LARGE)
            }
        }

        val keys = entries.map { it.first }
        if (keys.toSet().size != keys.size) {
            return rejected(CallPayloadRejectionReason.DUPLICATE_KEY)
        }
        if (entries.size != EXPECTED_KEYS.size || keys.toSet() != EXPECTED_KEYS) {
            return rejected(CallPayloadRejectionReason.INVALID_SHAPE)
        }

        val values = entries.toMap()
        val rawCallHandle = values.getValue("c")
        val wakeHandle = values.getValue("h")
        val expiryText = values.getValue("e")
        if (
            values.getValue("v") != "1" ||
            values.getValue("w") != "call" ||
            !CALL_RANDOM_ID.matches(rawCallHandle) ||
            !CALL_RANDOM_ID.matches(wakeHandle) ||
            !STRICT_MILLISECONDS.matches(expiryText)
        ) {
            return rejected(CallPayloadRejectionReason.MALFORMED)
        }

        val expiresAtMs = expiryText.toLongOrNull()
            ?: return rejected(CallPayloadRejectionReason.MALFORMED)
        val receivedAtMs = try {
            nowMs()
        } catch (_: Exception) {
            return rejected(CallPayloadRejectionReason.MALFORMED)
        }
        if (receivedAtMs < 0L) return rejected(CallPayloadRejectionReason.MALFORMED)
        if (expiresAtMs <= receivedAtMs) {
            return rejected(CallPayloadRejectionReason.STALE)
        }
        if (expiresAtMs - receivedAtMs > MAX_CALLER_EXPIRY_AHEAD_MS) {
            return rejected(CallPayloadRejectionReason.TOO_FAR_FUTURE)
        }

        val nativeCallId = nativeCallIdFromCallHandle(rawCallHandle)
        return CallPayloadParseResult.Accepted(
            CallWakePayload(
                nativeCallId = nativeCallId,
                callHandle = nativeCallId.toString(),
                wakeHandle = wakeHandle,
                receivedAtMs = receivedAtMs,
                expiresAtMs = expiresAtMs,
            ),
        )
    }

    private fun rejected(reason: CallPayloadRejectionReason) =
        CallPayloadParseResult.Rejected(reason)
}

// The call-control boundary intentionally accepts the two opaque 128-bit
// encodings already used by Mknoon: compact relay IDs and canonical UUID-v4
// IDs generated by the Dart signaling adapter. No other UUID version or
// mixed-case representation is admitted.
internal val CALL_RANDOM_ID = Regex(
    "^(?:[0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$",
)

internal val CANONICAL_CALL_HANDLE = Regex(
    "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
)

internal fun nativeCallIdFromCallHandle(callHandle: String): UUID {
    require(CALL_RANDOM_ID.matches(callHandle))
    if (callHandle.length == 36) return UUID.fromString(callHandle)
    return UUID.fromString(
        buildString(36) {
            append(callHandle, 0, 8)
            append('-')
            append(callHandle, 8, 12)
            append('-')
            append(callHandle, 12, 16)
            append('-')
            append(callHandle, 16, 20)
            append('-')
            append(callHandle, 20, 32)
        },
    )
}
