appId: ${APP_ID}
name: production_home_tabs
---
- runFlow:
    when:
      notVisible: '(?s)^Intros.*$'
    commands:
      - runFlow:
          when:
            platform: Android
          commands:
            - back
      - runFlow:
          when:
            platform: iOS
          commands:
            - tapOn: '^Back$'
- assertVisible: '(?s)^Intros.*$'
