appId: ${APP_ID}
name: production_group_info_add_member_retry
---
- assertVisible: 'Add Members \(1\)'
- tapOn: Send Invites
- extendedWaitUntil:
    visible: Group Info
    timeout: 20000
- back
- assertVisible:
    id: chat_composer
